// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// line_searcher
double line_searcher(arma::mat Co_x, arma::colvec Tr_total, arma::colvec coefs, arma::colvec Newton, arma::colvec Base_weight, arma::colvec alpha, double ss);
RcppExport SEXP _hbal_line_searcher(SEXP Co_xSEXP, SEXP Tr_totalSEXP, SEXP coefsSEXP, SEXP NewtonSEXP, SEXP Base_weightSEXP, SEXP alphaSEXP, SEXP ssSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Co_x(Co_xSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Tr_total(Tr_totalSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type coefs(coefsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Newton(NewtonSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Base_weight(Base_weightSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type ss(ssSEXP);
    rcpp_result_gen = Rcpp::wrap(line_searcher(Co_x, Tr_total, coefs, Newton, Base_weight, alpha, ss));
    return rcpp_result_gen;
END_RCPP
}
// hb
List hb(arma::colvec tr_total, arma::mat co_x, arma::colvec coefs, arma::colvec base_weight, arma::colvec alpha, int max_iterations, double constraint_tolerance, int print_level);
RcppExport SEXP _hbal_hb(SEXP tr_totalSEXP, SEXP co_xSEXP, SEXP coefsSEXP, SEXP base_weightSEXP, SEXP alphaSEXP, SEXP max_iterationsSEXP, SEXP constraint_toleranceSEXP, SEXP print_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type tr_total(tr_totalSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type co_x(co_xSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type coefs(coefsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type base_weight(base_weightSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type constraint_tolerance(constraint_toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type print_level(print_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(hb(tr_total, co_x, coefs, base_weight, alpha, max_iterations, constraint_tolerance, print_level));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hbal_line_searcher", (DL_FUNC) &_hbal_line_searcher, 7},
    {"_hbal_hb", (DL_FUNC) &_hbal_hb, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_hbal(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
