# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

line_searcher <- function(Co_x, Tr_total, coefs, Newton, Base_weight, alpha, ss) {
    .Call(`_hbal_line_searcher`, Co_x, Tr_total, coefs, Newton, Base_weight, alpha, ss)
}

hb <- function(tr_total, co_x, coefs, base_weight, alpha, max_iterations, constraint_tolerance, print_level) {
    .Call(`_hbal_hb`, tr_total, co_x, coefs, base_weight, alpha, max_iterations, constraint_tolerance, print_level)
}

